name: qiskit_vqc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - pip
  #- scikit-learn
  - pip:
      - scikit-learn<=1.1.3 
      - pyscf==2.8.0
      #- qiskit==0.44.0
      - qiskit==0.43.1
      - qiskit-aer==0.12.0
      #- qiskit-terra==0.25.0
      - qiskit-terra==0.24.1
      - qiskit-nature==0.6.2
      #- qiskit-machine-learning==0.6.1
      - qiskit-machine-learning==0.5.0
      - qiskit-algorithms==0.2.1
      - pylatexenc